# Generated by Django 5.0.3 on 2025-03-25 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeRateCR', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BanksInsights',
            new_name='BanksInsight',
        ),
    ]
