# Generated by Django 5.0.3 on 2024-03-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanCalculations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=300),
        ),
    ]
