# Generated by Django 5.0.3 on 2024-03-31 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loanCalculations', '0002_alter_comments_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
